spark:
  app_name: "Walmart Sales Analysis"
  master: "local[*]"
  spark_local_ip: "127.0.0.1"


datapaths:
  features: "data/features.csv"
  stores: "data/stores.csv"
  train: "data/train.csv"
  test: "data/test.csv"